
-- Xóa cấu trúc & dữ liệu (nếu có) trước khi tạo cấu trúc:
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DONVI CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SINHVIEN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOCPHAN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MOMON CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DANGKY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/


--
-- ACCOUNT
CREATE TABLE ACCOUNT (
    ID INT PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('ADMIN', 'NVCB', 'GV', 'NV PDT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV'))
);
INSERT INTO ACCOUNT (ID, username, password, VAITRO) VALUES (1, 'admin', 'admin123', 'ADMIN');

-- ĐƠN VỊ
CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100) NOT NULL,
    LOAIDV VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV VARCHAR2(10)
);

-- NHÂN VIÊN
CREATE TABLE NHANVIEN (
    MANLD VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    LUONG NUMBER(10,2) CHECK (LUONG >= 0),
    PHUCAP NUMBER(10,2) CHECK (PHUCAP >= 0),
    DT VARCHAR2(15),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')),
    MADV VARCHAR2(10),
    CONSTRAINT FK_NHANVIEN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);
ALTER TABLE DONVI 
ADD CONSTRAINT FK_DONVI_NHANVIEN FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANLD);
-- ALTER TABLE DONVI DROP CONSTRAINT FK_DONVI_NHANVIEN;

-- SINH VIÊN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(5) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    DCHI VARCHAR2(200),
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('Đang học', 'Nghỉ học', 'Bảo lưu')),
    CONSTRAINT FK_SINHVIEN_DONVI FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

-- HỌC PHẦN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100) NOT NULL,
    SOTC NUMBER(2) CHECK (SOTC > 0),
    STLT NUMBER(3) CHECK (STLT >= 0),
    STTH NUMBER(3) CHECK (STTH >= 0),
    MADV VARCHAR2(10),
    CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- MỞ MÔN
CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    CONSTRAINT FK_MOMON_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    CONSTRAINT FK_MOMON_NHANVIEN FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANLD)
);

-- ĐĂNG KÝ
CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAMM VARCHAR2(10),
    DIEMTH NUMBER(5,2) CHECK (DIEMTH BETWEEN 0 AND 10),
    DIEMQT NUMBER(5,2) CHECK (DIEMQT BETWEEN 0 AND 10),
    DIEMCK NUMBER(5,2) CHECK (DIEMCK BETWEEN 0 AND 10),
    DIEMTK NUMBER(5,2) CHECK (DIEMTK BETWEEN 0 AND 10),
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV, MAMM),
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_MOMON FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);