-- Câu 2: QUAN HE MOMON 
-- Người dùng có vai trò “GV” được quyền xem các dòng phân công giảng dạy liên quan
-- đến chính giảng viên đó

CREATE VIEW UV_GV_CANHAN AS
SELECT * FROM MOMON WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');
    GRANT SELECT ON UV_GV_CANHAN TO RL_GV;

-- Người dùng có vai trò “NV PĐT” có quyền xem, thêm, cập nhật, xóa dòng trong bảng
-- MOMON liên quan đến học kỳ hiện tại của năm học đang diễn ra.


CREATE OR REPLACE VIEW UV_NVPDT_MOMON AS 
SELECT *
FROM MOMON
WHERE 
    NAM = CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) >= 9 THEN EXTRACT(YEAR FROM SYSDATE)
        ELSE EXTRACT(YEAR FROM SYSDATE) - 1
    END
    AND HK = CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 9 AND 12 THEN 1
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 1 AND 4 THEN 2
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 5 AND 8 THEN 3
    END;

CREATE OR REPLACE TRIGGER TR_NVPDT_MOMON_INSERT 
INSTEAD OF INSERT ON UV_NVPDT_MOMON 
FOR EACH ROW
DECLARE
    v_current_year NUMBER := CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) >= 9 THEN EXTRACT(YEAR FROM SYSDATE)
        ELSE EXTRACT(YEAR FROM SYSDATE) - 1
    END;
    v_current_hk NUMBER := CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 9 AND 12 THEN 1
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 1 AND 4 THEN 2
        ELSE 3
    END;
BEGIN
    IF :NEW.NAM != v_current_year OR :NEW.HK != v_current_hk THEN
        RAISE_APPLICATION_ERROR(-20002, 'Chỉ được thêm môn mở cho học kỳ và năm học hiện tại.');
    END IF;

    INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM)
    VALUES (:NEW.MAMM, :NEW.MAHP, :NEW.MAGV, :NEW.HK, :NEW.NAM);
END;
/

CREATE OR REPLACE TRIGGER TR_NVPDT_MOMON_UPDATE 
INSTEAD OF UPDATE ON UV_NVPDT_MOMON 
FOR EACH ROW
DECLARE
    v_current_year NUMBER := CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) >= 9 THEN EXTRACT(YEAR FROM SYSDATE)
        ELSE EXTRACT(YEAR FROM SYSDATE) - 1
    END;
    v_current_hk NUMBER := CASE 
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 9 AND 12 THEN 1
        WHEN EXTRACT(MONTH FROM SYSDATE) BETWEEN 1 AND 4 THEN 2
        ELSE 3
    END;
BEGIN
    IF :NEW.NAM != v_current_year OR :NEW.HK != v_current_hk THEN
        RAISE_APPLICATION_ERROR(-20003, 'Chỉ được cập nhật môn mở cho học kỳ và năm học hiện tại.');
    END IF;

    UPDATE MOMON
    SET MAHP = :NEW.MAHP,
        MAGV = :NEW.MAGV,
        HK = :NEW.HK,
        NAM = :NEW.NAM
    WHERE MAMM = :OLD.MAMM; 
END;
/

CREATE OR REPLACE TRIGGER TR_NVPDT_MOMON_DELETE 
INSTEAD OF DELETE ON UV_NVPDT_MOMON 
FOR EACH ROW
BEGIN
    DELETE FROM MOMON
    WHERE MAMM = :OLD.MAMM; 
END;
/


GRANT SELECT, INSERT, UPDATE, DELETE ON UV_NVPDT_MOMON TO RL_NVPDT; 

-- Người dùng có vai trò “TRGĐV” có quyền xem các dòng phân công giảng dạy của
-- các giảng viên thuộc đơn vị mình làm trưởng
CREATE OR REPLACE VIEW UV_TRGDV_MOMON AS
SELECT MM.MAMM, MM.MAHP, HP.TENHP, MM.MAGV, NV.HOTEN AS TENGV, MM.HK, MM.NAM
FROM MOMON MM
JOIN NHANVIEN NV ON MM.MAGV = NV.MANLD
JOIN HOCPHAN HP ON MM.MAHP = HP.MAHP
WHERE NV.MADV IN (
    SELECT MADV
    FROM DONVI
    WHERE TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER')
);
-- Cấp quyền cho TRGDV trên view MOMON
GRANT SELECT ON UV_TRGDV_MOMON TO RL_TRDGV;

-- Sinh viên có quyền xem các dòng dữ liệu trong quan hệ MOMON liên quan các dòng
-- mở các học phần thuộc quyền phụ trách chuyên môn bởi Khoa mà sinh viên đang theo học.
CREATE OR REPLACE VIEW UV_SV_MOMON AS
SELECT MM.MAMM, MM.MAHP, HP.TENHP, NV.HOTEN AS TENGV, MM.HK, MM.NAM, DV.TENDV
FROM MOMON MM
JOIN HOCPHAN HP ON MM.MAHP = HP.MAHP
JOIN NHANVIEN NV ON MM.MAGV = NV.MANLD
JOIN DONVI DV ON HP.MADV = DV.MADV
WHERE HP.MADV = (  
    SELECT KHOA
    FROM SINHVIEN
    WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER')
);

GRANT SELECT ON UV_SV_MOMON TO RL_SV;